-- Root module for Computational Chemistry Free Energy Calculations
import HautevilleHouse.ComputationalChemistryFreeEnergyCalculationsCanonicalLaneLean.Basic
import HautevilleHouse.ComputationalChemistryFreeEnergyCalculationsCanonicalLaneLean.SourcePackage
import HautevilleHouse.ComputationalChemistryFreeEnergyCalculationsCanonicalLaneLean.SourceDependencies
import HautevilleHouse.ComputationalChemistryFreeEnergyCalculationsCanonicalLaneLean.Formalization
import HautevilleHouse.ComputationalChemistryFreeEnergyCalculationsCanonicalLaneLean.ReviewerBridge
import HautevilleHouse.ComputationalChemistryFreeEnergyCalculationsCanonicalLaneLean.TheoremStatement
import HautevilleHouse.ComputationalChemistryFreeEnergyCalculationsCanonicalLaneLean.MathlibObjects
import HautevilleHouse.ComputationalChemistryFreeEnergyCalculationsCanonicalLaneLean.AdmissibleClass
import HautevilleHouse.ComputationalChemistryFreeEnergyCalculationsCanonicalLaneLean.Projection
import HautevilleHouse.ComputationalChemistryFreeEnergyCalculationsCanonicalLaneLean.BridgeLemmas
import HautevilleHouse.ComputationalChemistryFreeEnergyCalculationsCanonicalLaneLean.GateLemmas
import HautevilleHouse.ComputationalChemistryFreeEnergyCalculationsCanonicalLaneLean.FinalTheorem
import HautevilleHouse.ComputationalChemistryFreeEnergyCalculationsCanonicalLaneLean.MathlibStatement